### ISSUE TITLE
Whether to support A12?

### ISSUE THREAD

**Issue by sgj413** [CoBrA2168/Sleeper#1]
I am using iphone XR, according to your description it is not supported

**Comment by joshuaseltzer** [comment]
The description is old and needs to be updated. It works on your device! 👍

**Comment by joshuaseltzer** [comment]
Just updated the README file with the appropriate compatibility.  At the time of writing, the tweak supports iOS 8 all the way through iOS 13.5 on all iOS devices (iPhones, iPads, iPod Touches).

If you want to support me with this tweak, feel free to download it from the Packix repo here:
https://repo.packix.com/package/org.packix.sleeper/

Thanks for your support!
